### ISSUE TITLE
Width prompt typo, and suggestions

### ISSUE THREAD

**Issue by NoneGiven** [desuwa/tegaki#2]
When creating a new canvas with "New" in the painter, the prompt for canvas width (first of the two prompts) says "Canvas height in pixels" instead of "width".

If possible, the canvas could be extended (but hidden) by a couple dozen pixels on each side, beyond the specified dimensions, to allow drawing "outside" the canvas and still having part of the brush apply inside the visible boundary. This is something Shii Painter can do (since unlike this HTML5 canvas, the whole page is an interactive area), and it makes a noticeable difference if you're trying to draw/fill along the edges. Then, when flattening the image and spitting out the PNG, the canvas would be cropped to the originally specified dimensions.

Also, any chance of keybind support?

**Comment by desuwa** [comment]
Should be fixed now, thanks.

>allow drawing "outside" the canvas
>keybind support

Sure.
