### ISSUE TITLE
If a page is scrolled a bit, drawing is offset

### ISSUE THREAD

**Issue by karai17** [desuwa/tegaki#5]
If you load Tegaki while your webpage is not at the very top of the scroll area, then trying to draw causes your cursor to be offset by the same amount that you are scrolled.

**Comment by desuwa** [comment]
This only seems to happen when the page is scrolled *after* the Tegaki is loaded/displayed (keyboard arrows, middle mouse button scroll, etc...)

**Comment by karai17** [comment]
Thanks for the quick fix! <3
